

name: Deploy en runner local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Adquion-Frontend]
    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install
        working-directory: deploy/Adquion-Plataform

      - name: Ejecutar deploy
        run: npm run deploy
        working-directory: deploy/Adquion-Plataform
